nba_stat_dict = {
'min': 0,
'fgs': 1,
'fg_percent': 2,
'3-PT Made': 3,
'three_percent': 4,
'ft': 5,
'ft_percent': 6,
'Rebounds': 7,
'Assists': 8,
'Blocked Shots': 9,
'Steals': 10,
'fouls': 11,
'Turnovers': 12,
'Points': 13,
}

nfl_stat_dict = {
    'QB': 
        {'Pass Completions': 0,
        'Pass Attempts': 1,
        'Pass Yards': 2,
        'comp_percent': 3,
        'avg': 4,
        'Pass TDs': 5,
        'INT': 6,
        'long': 7,
        'sack': 8,
        'RTG': 9,
        'QBR': 10,
        'rush_att': 11,
        'Rush Yards': 12,
        'rush_avg': 13,
        'Rush TDs': 14,
        'rush_long': 15},
    'WR':
        {'Receptions': 0,
        'Targets': 1,
        'Receiving Yards': 2,
        'Avg': 3,
        'Rec TDs': 4,
        'Long': 5,
        'Rush Attempts': 6,
        'Rush Yards': 7,
        'Rush Avg': 8,
        'Rush Long': 9,
        'Rush TDs': 10,
        },
    'TE':
        {
        'Receptions': 0,
        'Targets': 1,
        'Receiving Yards': 2,
        'Avg': 3,
        'Rec TDs': 4,
        'Long': 5,
        'Rush Attempts': 6,
        'Rush Yards': 7,
        'Rush Avg': 8,
        'Rush Long': 9,
        'Rush TDs': 10,
        },
    'RB':
        {
        'Rush Attempts': 0,
        'Rush Yards': 1,
        'Rush Avg': 2,
        'Rush TDs': 3,
        'Rush Long': 4,
        'Receptions': 5,
        'Targets': 6,
        'Receiving Yards': 7,
        'Avg': 8,
        'Rec TDs': 9,
        'Long': 10,
        }
}



pp_abv_to_espn_abv = {
    'ATL': 'ATL', 
    'BKN': 'BKN', 
    'BOS': 'BOS', 
    'CHA': 'CHA', 
    'CHI': 'CHI', 
    'CLE': 'CLE', 
    'DAL': 'DAL', 
    'DEN': 'DEN', 
    'DET': 'DET', 
    'GSW': 'GS', 
    'HOU': 'HOU', 
    'IND': 'IND', 
    'LAC': 'LAC', 
    'LAL': 'LAL', 
    'MEM': 'MEM',
    'MIA': 'MIA', 
    'MIL': 'MIL', 
    'MIN': 'MIN', 
    'NOP': 'NO', 
    'NYK': 'NY', 
    'OKC': 'OKC', 
    'ORL': 'ORL', 
    'PHI': 'PHI', 
    'PHX': 'PHX', 
    'POR': 'POR', 
    'SAC': 'SAC', 
    'SAS': 'SA', 
    'TOR': 'TOR', 
    'UTA': 'UTAH', 
    'WAS': 'WSH'}